<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAX9mRnS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAX9mRnS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAX9mRnS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAX9mRnS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAX9mRnS\App_KernelDevDebugContainer([
    'container.build_hash' => 'AX9mRnS',
    'container.build_id' => '7e10f1d7',
    'container.build_time' => 1684912907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAX9mRnS');
