<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDava6Wf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDava6Wf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDava6Wf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDava6Wf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDava6Wf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Dava6Wf',
    'container.build_id' => '1162d9ed',
    'container.build_time' => 1684930905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDava6Wf');
